GET https://apis.data.go.kr/1051000/MoefOpenAPI/T_OPD_PRMSCT_SBBGST?serviceKey=24%2BxY3FOTGQExKs%2BgXvH8yTBk8ddPvKVpMX%2B1u9QEAwqYmiiulEgIfX%2BBBcG0Lzb6DtfHnJ%2BckJ%2BEzsyMoifzQ%3D%3D&pageNo=1&numOfRows=10&resultType=json&bsnsyear=2021&realm_nm=%EC%9D%BC%EB%B0%98%C2%B7%EC%A7%80%EB%B0%A9%ED%96%89%EC%A0%95